/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function buildObject(): Built

export interface Built {
  name: string
  version: number
}

export declare function getNumber(arg: number): number

export declare function makeArray(n: number): Array<number>

export declare function plus100(input: number): number

export declare function sum(a: number, b: number): number
